### ISSUE TITLE
Fianl iteration issues

### ISSUE THREAD

**Issue by YairFrank** [jamesgleave/Deep-Docking-NonAutomated#10]
Hi,
During the final iteration when running **Extracting_smiles.py**, two issues were identified:

1. line 177:
`os.mkdir(file_path + '/' + protein + '/after_iteration/to_dock/smile')`
**os.mkdir** can only create one directory and in this case, 3 are needed. So maybe **os.makedirs** is more suitable here, otherwise the directories will not be created.

2. line 17:
Since **-sd** argument isn't available yet, there are problems later in the run:
**files** and **return_mols_per_file** lists are empty and therefore **get_mol_final** function can't be performed.
The exception I got is:

> Traceback (most recent call last):
>   File "Extracting_smiles.py", line 225, in <module>
>     'rb') as ref:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/gnss/yairf/DD_2021/wd/after_iteration/to_dock/to_dock_0.pickle'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Extracting_smiles.py", line 229, in <module>
>     'r') as ref:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/gnss/yairf/DD_2021/wd/after_iteration/to_dock/to_dock_0.txt'

Thank you for your support,
Yair Frank

**Comment by YairFrank** [comment]
Another thing I wonder about is at what stage are files created within the directory:
**after_iteration/to_dock/**
Even if the **get_mol_final** function works, it will not be able to read the files because they do not seem to exist, and the same exception will be raised even then.

**Comment by fgentile89** [comment]
Hi, thanks for pointing out this and sorry for the delay. That parser is misleading as it was not intended to be used in the last iteration, but rather after the last iteration is completed. It is now replaced by the final phase scripts for that purpose, so in phase 1 of the final iteration, you can set the argument to False. We will replace that script soon

Francesco

**Comment by jyaacoub** [comment]
The Extracting_smiles.py file has been updated with those deprecated options removed to avoid future confusion. I also updated the readme to reflect the change. Thanks again for bringing this issue up!
