### ISSUE TITLE
best_model_stats

### ISSUE THREAD

**Issue by albertma-evotec** [jamesgleave/Deep-Docking-NonAutomated#12]
In the protein folder, in best_model_stats.txt, what does the Total Left Testing number mean? 
![image](https://user-images.githubusercontent.com/54853041/123274452-6fa69500-d4fb-11eb-9b2f-5904d0885545.png)

FYI, The database I am using has a total size of 3.8M compounds, and in iteration 1 I sampled 9999 for each training/validation/testing set. 

Thanks

**Comment by fgentile89** [comment]
Hi,
the total left testing is the predicted number of molecules that will be retained (classified as virtual hits) based on the stats of the test set. If the models are generalizable, it should be quite close to what you will really see once you run the inference phase

Francesco
