### ISSUE TITLE
final_phase

### ISSUE THREAD

**Issue by albertma-evotec** [jamesgleave/Deep-Docking-NonAutomated#14]
Hi 
I have run the final phase script. I found the file generated file does not contain all of the compounds in the database.
I have ~3.8M compounds in db. The generated file (id_score.csv) only contains ~1.4M. Is it normal at all? Is it because the missing ones have already been predicted to be non-hit and eliminated in the workflow iteration?

Thanks

**Comment by jyaacoub** [comment]
I hope you were able to solve this, I am sorry we didn't get to you sooner. 

But yes this is normal, during the DD process at each iteration the program prunes molecules that are nowhere near optimal docking scores so that you are left with the most relevant molecules at the end.
