### ISSUE TITLE
Sign of docking score relevant?

### ISSUE THREAD

**Issue by georgkempf** [jamesgleave/Deep-Docking-NonAutomated#17]
When using Glide for docking, good scores have a negative sign and the smaller the number, the better the score would be (-12 better than +3 for example). What happens to the sign when the scores are fed to the model? Does it have a relevance on the interpretation of predictions when smaller score numbers correspond to a better hit?

**Comment by fgentile89** [comment]
Hi,
Deep docking works with "the lower the better" for scores, just as you
said. Most if not all docking programs use binding energies thus the lower
the better ( considering signs too). Cheers
