### ISSUE TITLE
extracting_smiles code in phase 1

### ISSUE THREAD

**Issue by albertma-evotec** [jamesgleave/Deep-Docking-NonAutomated#18]
![image](https://user-images.githubusercontent.com/54853041/148380806-13bccdb9-a104-481a-9420-d9560555a1bf.png)
Hi, did I miss anything here as I cannot see what it is trying to do here?

**Comment by jyaacoub** [comment]
Hi @albertma-evotec apologies for the late reply, but I have been looking into this and I believe that this was legacy code and doesn't do anything.

I will remove it to avoid future confusion, thanks for bringing this up!
