### ISSUE TITLE
ML package

### ISSUE THREAD

**Issue by YairFrank** [jamesgleave/Deep-Docking-NonAutomated#5]
Hello,
I'm trying to use this tool on a small dataset.
When running 'progressive_docking.py', this line (19):
```
from ML.DDModel import DDModel
```
raises this error:

> `ModuleNotFoundError: No module named 'ML'`

What is 'ML'? Is this something that needs to be installed?

Thank you,
Yair Frank

**Comment by albertma-evotec** [comment]
Hello

Same error here. There is no information about this module????

Albert

**Comment by albertma-evotec** [comment]
Seems someone forget to upload the private "ML" module? It does not sound to be publicly available anywhere

**Comment by YairFrank** [comment]
I think so, too

**Comment by fgentile89** [comment]
You're right, somehow the ML module was not included in our upload, we will fix this very soon

**Comment by YairFrank** [comment]
Thank you

**Comment by fgentile89** [comment]
Let us known if you still have problems
