### ISSUE TITLE
simple_job_models file

### ISSUE THREAD

**Issue by albertma-evotec** [jamesgleave/Deep-Docking-NonAutomated#6]
Hi 

I am running some test using a much smaller database (4.8M)
I do not quite understand what some of the variables in the code actually mean 
t_mol
first_mols

and 
`parser.add_argument("-ct", required=False, default=0.9, help="Recall, [0,1] range")`

why is this ct default to be 0.9? what is the point of this variable? It seems to be just a counter incremented by 1 in the for loop at the end.

**Comment by fgentile89** [comment]
Hi,

- `t_mol` is the the total number of molecules in the database (in millions). It is calculated from the Mol_ct_file.csv generated in phase 1 (line 79)

-  `first_mols` is the number of top scoring molecules considered as top scoring in the first iteration, over iterations this will linearly change from this value to `last_mols`. You can control this from percent_first_mols and percent_last_mols, see line 116 (we usually use 1 and 0.01, the values we used for the paper).

-  `ct` was supposed to be the recall value (set to 0.9 as default like in the paper). The counter was wrongly called in the same way and the value was not passed to progressive_docking.py, so it would have been always 0.9, but we have fixed this now, and you can pass whatever value you prefer.
